[package]
name = "integer_exponentiation"
version = "0.1.0"
authors = ["Howard Huang <howeih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.2"
num-traits = "0.2.8"
rand = "0.6.5"